In [1]:
import numpy as np

print("Enter 3x3 Matrix A:")
A = np.array([list(map(float, input().split())) for _ in range(3)])

print("Enter 3x3 Matrix B:")
B = np.array([list(map(float, input().split())) for _ in range(3)])

add = A + B
sub = A - B
mul = A * B
div = np.divide(A, B, where=B != 0)

print("\nMatrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nA + B:\n", add)
print("\nA - B:\n", sub)
print("\nA * B (element-wise):\n", mul)
print("\nA / B (element-wise):\n", div)


Enter 3x3 Matrix A:


 1 2 3 
 1 3 4
 1 3 4


Enter 3x3 Matrix B:


 1 2 3
 1 4 5 
 5 6 7



Matrix A:
 [[1. 2. 3.]
 [1. 3. 4.]
 [1. 3. 4.]]

Matrix B:
 [[1. 2. 3.]
 [1. 4. 5.]
 [5. 6. 7.]]

A + B:
 [[ 2.  4.  6.]
 [ 2.  7.  9.]
 [ 6.  9. 11.]]

A - B:
 [[ 0.  0.  0.]
 [ 0. -1. -1.]
 [-4. -3. -3.]]

A * B (element-wise):
 [[ 1.  4.  9.]
 [ 1. 12. 20.]
 [ 5. 18. 28.]]

A / B (element-wise):
 [[1.         1.         1.        ]
 [1.         0.75       0.8       ]
 [0.2        0.5        0.57142857]]
